%% Preliminary setup
%%
clear
changeCobraSolver('ibm_cplex','LP');
rng default
if not(isfolder('..\data\results'))
    mkdir('..\data\results')
end
addpath(genpath('..\data\'))

% Specify parameters:
save_results = true;





%% Initialize data
%%
load constraint_data.mat
load DoE_data.mat
load critical_temperatures.mat
load iEC1356_Bl21DE3.mat
load BL21_gene_ID_map.mat
load exploration_cytotoxicities.mat
load optimization_cytotoxicities.mat

constraint_data.lbs = [constraint_data.exploration_lbs; constraint_data.optimization_lbs];
DoE_data.data = [DoE_data.exploration_data; DoE_data.optimization_data];
cytotoxicities = [exploration_cytotoxicities; optimization_cytotoxicities];

% get RNA base frequencies for the product protein
[A_freq, U_freq, C_freq, G_freq] = get_RNA_base_frequences();
A_freq = num2str(A_freq / 30);
U_freq = num2str(U_freq / 30);
C_freq = num2str(C_freq / 30);
G_freq = num2str(G_freq / 30);

% add heterologous production to the reactions
iEC1356_Bl21DE3 = addMetabolite(iEC1356_Bl21DE3, 'product[c]', 'Protein product in cytoplasm');
iEC1356_Bl21DE3 = addReaction(iEC1356_Bl21DE3, 'PRODUCTtranslation1', ...
    'reactionFormula', ['3 ala__L[c] + 6 asp__L[c] + 1 gln__L[c] + 3 gly[c] + ' ...
    '3 leu__L[c] + 2 lys__L[c] + 2 met__L[c] + 1 pro__L[c] + 2 ser__L[c] + 2 thr__L[c] + ' ...
    '1 tyr__L[c] + 2 val__L[c] + 3 alatrna[c] + 6 asptrna[c] + 1 glntrna[c] + 3 glytrna[c] + ' ...
    '3 leutrna[c] + 2 lystrna[c] + 2 mettrna[c] + 1 protrna[c] + 2 sertrna[c] + 2 thrtrna[c] + ' ...
    '1 tyrtrna[c] + 2 valtrna[c] + ' C_freq ' ctp[c] + ' G_freq ' gtp[c] + ' A_freq ' atp[c] + ' U_freq ' utp[c] + 117.6 atp[c] -> ' ...
    'translation_complex[c]'], ...
    'printLevel', 0);
iEC1356_Bl21DE3 = addReaction(iEC1356_Bl21DE3, 'PRODUCTtranslation2', ...
    'reactionFormula', ['translation_complex[c] -> ' ...
    '3 trnaala[c] + 6 trnaasp[c] + 1 trnagln[c] + 3 trnagly[c] + ' ...
    '3 trnaleu[c] + 2 trnalys[c] + 2 trnamet[c] + 1 trnapro[c] + 2 trnaser[c] + 2 trnathr[c] + ' ...
    '1 trnatyr[c] + 2 trnaval[c] + ' C_freq ' ctp[c] + ' G_freq ' gtp[c] + ' A_freq ' atp[c] + ' U_freq ' utp[c] + product[c] + 117.6 adp[c] + 117.6 pi[c]'], ...
    'printLevel', 0);

% rescale "infinity" bounds
iEC1356_Bl21DE3.lb(iEC1356_Bl21DE3.lb == -1000) = -100;
iEC1356_Bl21DE3.ub(iEC1356_Bl21DE3.ub == 1000) = 100;

% convert gene names in the "genes" field into "b****" identifiers
for i = 1:length(iEC1356_Bl21DE3.genes)
    if isKey(BL21_gene_ID_map, iEC1356_Bl21DE3.genes(i))
        iEC1356_Bl21DE3.genes{i} = BL21_gene_ID_map(iEC1356_Bl21DE3.genes{i});
    end
end
% merge duplicate genes (1 per model)
[~, ia] = unique(iEC1356_Bl21DE3.genes);
duplicate_idxs = setdiff(1:length(iEC1356_Bl21DE3.genes), ia);
[iEC1356_Bl21DE3] = mergeModelFieldPositions(iEC1356_Bl21DE3, 'genes', strcmp(iEC1356_Bl21DE3.genes, iEC1356_Bl21DE3.genes{duplicate_idxs}));
% generate the grRules and the rxnGeneMat fields
iEC1356_Bl21DE3 = creategrRulesField(iEC1356_Bl21DE3);
iEC1356_Bl21DE3 = buildRxnGeneMat(iEC1356_Bl21DE3);

% fix subsystems as they are missing from the models
iEC1356_Bl21DE3 = set_subSystems(iEC1356_Bl21DE3);

% set nutritional constraints
[nutrient_rxns, ~] = define_nutrient_constraints();
iEC1356_Bl21DE3 = changeRxnBounds(iEC1356_Bl21DE3, nutrient_rxns, -10, 'l');
excRxns = iEC1356_Bl21DE3.rxns(findExcRxns(iEC1356_Bl21DE3));
iEC1356_Bl21DE3 = changeRxnBounds(iEC1356_Bl21DE3, excRxns(not(ismember(excRxns, nutrient_rxns))), 0, 'l'); % block import of metabolites not in medium
iEC1356_Bl21DE3 = changeRxnBounds(iEC1356_Bl21DE3, excRxns, 100, 'u'); % unlimited export of all metabolites

% get irreversible models
[iEC1356_Bl21DE3_irrev, ~, ~, ~,] = convertToIrreversible(iEC1356_Bl21DE3);
[rxns, idxs, ~] = unique(iEC1356_Bl21DE3_irrev.rxns);
subSystems = iEC1356_Bl21DE3_irrev.subSystems;
subSystems = subSystems(idxs(idxs ~= 0));
constraint_data.rxns = strcat(constraint_data.rxns, repmat({'_b'}, [1, length(constraint_data.rxns)]));

% check that FBA works
iEC1356_Bl21DE3_irrev = changeObjective(iEC1356_Bl21DE3_irrev, 'BIOMASS_Ec_iJO1366_WT_53p95M');
FBAsolution = optimizeCbModel(iEC1356_Bl21DE3_irrev);
disp(['iEC1356_Bl21DE3 base biomass :  ', num2str(FBAsolution.f)])

% compute data for gene set rule propagation
if isfile('..\data\processed\reaction_expression_data_BL21')
    load reaction_expression_data_BL21.mat
else
    [reaction_expression_BL21, pos_genes_in_react_expr_BL21, ixs_geni_sorted_by_length_BL21] = compute_reaction_expression(iEC1356_Bl21DE3_irrev);
    save('..\data\processed\reaction_expression_data_BL21', 'reaction_expression_BL21', 'pos_genes_in_react_expr_BL21', 'ixs_geni_sorted_by_length_BL21')
end





%% Condition-specific simulations for post-induction phase
%%
% calculate [0,1]-normalised growth
zgrowth = (max(DoE_data.data.IPTG) - DoE_data.data.IPTG) ./ ...
    (max(DoE_data.data.IPTG) - min(DoE_data.data.IPTG));

% get total protein contribution to biomass
protein_biomass_sum = abs(sum(iEC1356_Bl21DE3.S(ismember(iEC1356_Bl21DE3.mets, {'ala__L[c]','arg__L[c]','asn__L[c]','asp__L[c]', ...
    'cys__L[c]','glu__L[c]','gln__L[c]','gly[c]','his__L[c]','ile__L[c]','leu__L[c]','lys__L[c]','met__L[c]','phe__L[c]','pro__L[c]', ...
    'ser__L[c]','thr__L[c]','trp__L[c]','tyr__L[c]','val__L[c]'}), ...
    strcmp(iEC1356_Bl21DE3.rxns, 'BIOMASS_Ec_iJO1366_WT_53p95M'))));

num_conditions = size(DoE_data.data, 1);
fluxes = zeros(num_conditions, length(rxns));
predicted_atp_post = NaN(num_conditions, 1);
predicted_production_post = NaN(num_conditions, 1);

for i = 1:num_conditions
    % generate condition-specific model
    bioreactor_model = iEC1356_Bl21DE3_irrev;
    bioreactor_model = change_enzyme_activity(bioreactor_model, critical_temperatures, double(string(DoE_data.data.T(i))), ...
        reaction_expression_BL21, pos_genes_in_react_expr_BL21, ixs_geni_sorted_by_length_BL21, ...
        0.00, 0.5, 0.5, 0);
    
    % set uptake constraints
    bioreactor_model = changeRxnBounds(bioreactor_model, constraint_data.rxns, -constraint_data.lbs(i, :), 'l');
    
    % include the product in biomass
    bioreactor_model.S(strcmp(bioreactor_model.mets, 'product[c]'), strcmp(bioreactor_model.rxns, 'BIOMASS_Ec_iJO1366_WT_53p95M')) = ...
        (-0.01 - 0.39*(1-zgrowth(i)))*protein_biomass_sum;
    bioreactor_model.S(ismember(bioreactor_model.mets, {'ala__L[c]','arg__L[c]','asn__L[c]','asp__L[c]', ...
    'cys__L[c]','glu__L[c]','gln__L[c]','gly[c]','his__L[c]','ile__L[c]','leu__L[c]','lys__L[c]','met__L[c]','phe__L[c]','pro__L[c]', ...
    'ser__L[c]','thr__L[c]','trp__L[c]','tyr__L[c]','val__L[c]'}), ...
        strcmp(bioreactor_model.rxns, 'BIOMASS_Ec_iJO1366_WT_53p95M')) = ...
        bioreactor_model.S(ismember(bioreactor_model.mets, {'ala__L[c]','arg__L[c]','asn__L[c]','asp__L[c]', ...
    'cys__L[c]','glu__L[c]','gln__L[c]','gly[c]','his__L[c]','ile__L[c]','leu__L[c]','lys__L[c]','met__L[c]','phe__L[c]','pro__L[c]', ...
    'ser__L[c]','thr__L[c]','trp__L[c]','tyr__L[c]','val__L[c]'}), ...
        strcmp(bioreactor_model.rxns, 'BIOMASS_Ec_iJO1366_WT_53p95M')) * (0.6 + 0.39*zgrowth(i));
    
    % growth constraints
    FBAsolution = optimizeCbModel(bioreactor_model);
    bioreactor_model = changeRxnBounds(bioreactor_model, 'BIOMASS_Ec_iJO1366_WT_53p95M', ...
        0.9 * FBAsolution.f, 'l');
    
    % calculate fluxes
    bioreactor_model = changeObjective(bioreactor_model, 'ATPM');
    [FBAsolution, ~] = my_pFBA(bioreactor_model, 0);
    [a, b] = ismember(rxns, bioreactor_model.rxns);
    fluxes(i, a) = FBAsolution.v(b(a));
    predicted_atp_post(i) = FBAsolution.v(strcmp(bioreactor_model.rxns, 'ATPM'));
    predicted_production_post(i) = FBAsolution.v(strcmp(bioreactor_model.rxns, 'PRODUCTtranslation2'));
end

% Save results:
if save_results == true
    save('..\data\results\postinduction_pFBA_fluxes.mat', 'fluxes', 'rxns', 'subSystems')
    save('..\data\results\postinduction_pFBA_data.mat')
end





%% Condition-specific simulations for end-of-process  phase
%%
% calculate [0,1]-normalised growth
zgrowth = (max(cytotoxicities) - cytotoxicities) ./ ...
    (max(cytotoxicities) - min(cytotoxicities));

% get total protein contribution to biomass
protein_biomass_sum = abs(sum(iEC1356_Bl21DE3.S(ismember(iEC1356_Bl21DE3.mets, {'ala__L[c]','arg__L[c]','asn__L[c]','asp__L[c]', ...
    'cys__L[c]','glu__L[c]','gln__L[c]','gly[c]','his__L[c]','ile__L[c]','leu__L[c]','lys__L[c]','met__L[c]','phe__L[c]','pro__L[c]', ...
    'ser__L[c]','thr__L[c]','trp__L[c]','tyr__L[c]','val__L[c]'}), ...
    strcmp(iEC1356_Bl21DE3.rxns, 'BIOMASS_Ec_iJO1366_WT_53p95M'))));

num_conditions = size(DoE_data.data, 1);
fluxes = zeros(num_conditions, length(rxns));
predicted_atp_post = NaN(num_conditions, 1);
predicted_production_post = NaN(num_conditions, 1);

for i = 1:num_conditions
    % generate condition-specific model
    bioreactor_model = iEC1356_Bl21DE3_irrev;
    bioreactor_model = change_enzyme_activity(bioreactor_model, critical_temperatures, double(string(DoE_data.data.T(i))), ...
        reaction_expression_BL21, pos_genes_in_react_expr_BL21, ixs_geni_sorted_by_length_BL21, ...
        0.00, 0.5, 0.5, 0);
    
    % set uptake constraints
    bioreactor_model = changeRxnBounds(bioreactor_model, constraint_data.rxns, -constraint_data.lbs(i, :), 'l');
    
    % include the product in biomass
    bioreactor_model.S(strcmp(bioreactor_model.mets, 'product[c]'), strcmp(bioreactor_model.rxns, 'BIOMASS_Ec_iJO1366_WT_53p95M')) = ...
        (-0.01 - 0.39*(1-zgrowth(i)))*protein_biomass_sum;
    bioreactor_model.S(ismember(bioreactor_model.mets, {'ala__L[c]','arg__L[c]','asn__L[c]','asp__L[c]', ...
    'cys__L[c]','glu__L[c]','gln__L[c]','gly[c]','his__L[c]','ile__L[c]','leu__L[c]','lys__L[c]','met__L[c]','phe__L[c]','pro__L[c]', ...
    'ser__L[c]','thr__L[c]','trp__L[c]','tyr__L[c]','val__L[c]'}), ...
        strcmp(bioreactor_model.rxns, 'BIOMASS_Ec_iJO1366_WT_53p95M')) = ...
        bioreactor_model.S(ismember(bioreactor_model.mets, {'ala__L[c]','arg__L[c]','asn__L[c]','asp__L[c]', ...
    'cys__L[c]','glu__L[c]','gln__L[c]','gly[c]','his__L[c]','ile__L[c]','leu__L[c]','lys__L[c]','met__L[c]','phe__L[c]','pro__L[c]', ...
    'ser__L[c]','thr__L[c]','trp__L[c]','tyr__L[c]','val__L[c]'}), ...
        strcmp(bioreactor_model.rxns, 'BIOMASS_Ec_iJO1366_WT_53p95M')) * (0.6 + 0.39*zgrowth(i));
    
    % growth constraints
    FBAsolution = optimizeCbModel(bioreactor_model);
    bioreactor_model = changeRxnBounds(bioreactor_model, 'BIOMASS_Ec_iJO1366_WT_53p95M', ...
        0.9 * FBAsolution.f, 'l');
    
    % calculate fluxes
    bioreactor_model = changeObjective(bioreactor_model, 'ATPM');
    [FBAsolution, ~] = my_pFBA(bioreactor_model, 0);
    [a, b] = ismember(rxns, bioreactor_model.rxns);
    fluxes(i, a) = FBAsolution.v(b(a));
    predicted_atp_post(i) = FBAsolution.v(strcmp(bioreactor_model.rxns, 'ATPM'));
    predicted_production_post(i) = FBAsolution.v(strcmp(bioreactor_model.rxns, 'PRODUCTtranslation2'));
end

% Save results:
if save_results == true
    save('..\data\results\end_pFBA_fluxes.mat', 'fluxes', 'rxns', 'subSystems')
    save('..\data\results\end_pFBA_data.mat')
end





%% Functions
%%

function [A_frequence, U_frequence, C_frequence, G_frequence] = get_RNA_base_frequences()
    % nucleotide sequence of length 28*3 of the p28 peptide
    % https://www.ncbi.nlm.nih.gov/datasets/gene/878046/#summary

    sequence = ...
        ['CTGAGCACCGCCGCCGACATGCAGGGCGTGGTCACCGACGGCATGGCTTCCGGCCTG' ...
        'GACAAGGATTACCTGAAGCCCGACGAC'];
    A_frequence = count(sequence, 'A');
    U_frequence = count(sequence, 'T');
    C_frequence = count(sequence, 'C');
    G_frequence = count(sequence, 'G');

end

function model = set_subSystems(model)
    % load table containing subsystem annotation from Monk et al 2016
    pathway_table = readtable('Ecoli_reactions_subsystems.xlsx', 'Sheet', 'Ecoli_reactions_subsystems');
    % load complete reaction table from BIGG to map old rxn IDs
    bigg_table = readtable('bigg_models_reactions.xlsx', 'Sheet', 'bigg_models_reactions');
    % set missing pathway information
    pathway_table.Subsystem(contains(pathway_table.Reaction, 'EX_')) = {'Pseudo-reactions'};
    pathway_table.Subsystem(contains(pathway_table.Reaction, 'DM_')) = {'Pseudo-reactions'};
    pathway_table.Subsystem(strcmp(pathway_table.Reaction, 'Ec_biomass_iJO1366_WT_53p95M')) = {'Pseudo-reactions'};
    pathway_table.Subsystem(strcmp(pathway_table.Reaction, 'Ec_biomass_iJO1366_core_53p95M')) = {'Pseudo-reactions'};
    pathway_table.Subsystem(strcmp(pathway_table.Subsystem, '')) = {'Unassigned'};
    % homogenise reactions names with those in models
    for i = 1:length(pathway_table.Reaction)
        if contains(pathway_table.Reaction{i}, '_DASH_LPAREN_e_RPAREN_')
            s = strsplit(pathway_table.Reaction{i}, '_DASH_LPAREN_e_RPAREN_');
            pathway_table.Reaction{i} = [s{1} '_e'];
        end
        if contains(pathway_table.Reaction{i}, '_DASH_D_RPAREN_e_LPAREN_')
            s = strsplit(pathway_table.Reaction{i}, '_DASH_D_RPAREN_e_LPAREN_');
            pathway_table.Reaction{i} = [s{1} '__D_e'];
        end
        if contains(pathway_table.Reaction{i}, 'DASH_R_DASH_L_LPAREN_e_RPAREN_')
            s = strsplit(pathway_table.Reaction{i}, 'DASH_R_DASH_L_LPAREN_e_RPAREN_');
            pathway_table.Reaction{i} = [s{1} '_R__L_e'];
        end
        if contains(pathway_table.Reaction{i}, 'DASH_S_DASH_L_LPAREN_e_RPAREN_')
            s = strsplit(pathway_table.Reaction{i}, 'DASH_S_DASH_L_LPAREN_e_RPAREN_');
            pathway_table.Reaction{i} = [s{1} '_S__L_e'];
        end
        if contains(pathway_table.Reaction{i}, '_LPAREN_e_RPAREN_')
            s = strsplit(pathway_table.Reaction{i}, '_LPAREN_e_RPAREN_');
            pathway_table.Reaction{i} = [s{1} '_e'];
        end
        if contains(pathway_table.Reaction{i}, '_DASH_')
            s = strsplit(pathway_table.Reaction{i}, '_DASH_');
            pathway_table.Reaction{i} = [s{1} '__' s{2}];
        end
    end
    pathway_table.Reaction(strcmp(pathway_table.Reaction, 'Ec_biomass_iJO1366_WT_53p95M')) = {'BIOMASS_Ec_iJO1366_WT_53p95M'};
    pathway_table.Reaction(strcmp(pathway_table.Reaction, 'Ec_biomass_iJO1366_core_53p95M')) = {'BIOMASS_Ec_iJO1366_core_53p95M'};

    for i = 1:length(model.rxns)
        if contains(model.rxns{i}, '_copy1')
            s = strsplit(model.rxns{i}, '_copy1');
            model.rxns{i} = s{1};
        end
        if contains(model.rxns{i}, '_copy2')
            s = strsplit(model.rxns{i}, '_copy2');
            model.rxns{i} = s{1};
        end
    end
    
    % map old rxn IDs through the BIGG table
    idxs = find(not(ismember(model.rxns, pathway_table.Reaction)) & not(contains(model.rxns, 'PRODUCT')));
    for i = 1:length(idxs)
        idx = strcmp(bigg_table.bigg_id, model.rxns(idxs(i)));
        old_ids = strsplit(bigg_table.old_bigg_ids{idx}, '; ');
        [a, b] = ismember(old_ids, pathway_table.Reaction);
        if sum(a) > 1
            a = and(a, not(contains(old_ids, 'R_DM_')));
            pathway_table.Reaction(b(a)) = bigg_table.bigg_id(idx);
        else
            pathway_table.Reaction(b(a)) = bigg_table.bigg_id(idx);
        end
    end
    
    % assign subsystems to reactions
    [a, b] = ismember(model.rxns, pathway_table.Reaction);
    model.subSystems(a) = pathway_table.Subsystem(b(a));
    model.subSystems(contains(model.rxns, 'PRODUCT')) = {'Heterologous production'};
end

function [uptakes, uptake_names] = define_nutrient_constraints()
    % source https://www.sigmaaldrich.com/catalog/product/sial/07533
    
    yeast_extract_uptakes = {'EX_thm_e', ... % vitamins
        'EX_nac_e', ...
        'EX_pnto__R_e', ...
        'EX_pydam_e', ...
        'EX_pydx_e', ...
        'EX_pydxn_e', ...
        'EX_btn_e', ...
        'EX_adocbl_e', ...
        'EX_cbi_e', ...
        'EX_cbl1_e', ...
        'EX_inost_e', ...
        'EX_ascb__L_e', ...
        'EX_chol_e', ...
        'EX_ala_B_e', ... % aminoacids
        'EX_ala__D_e', ...
        'EX_ala__L_e', ...
        'EX_arg__L_e', ...
        'EX_asn__L_e', ...
        'EX_asp__L_e', ...
        'EX_cys__D_e', ...
        'EX_cys__L_e', ...
        'EX_glu__L_e', ...
        'EX_gln__L_e', ...
        'EX_gly_e', ...
        'EX_his__L_e', ...
        'EX_ile__L_e', ...
        'EX_leu__L_e', ...
        'EX_lys__L_e', ...
        'EX_met__D_e', ...
        'EX_met__L_e', ...
        'EX_phe__L_e', ...
        'EX_pro__L_e', ...
        'EX_ser__D_e', ...
        'EX_ser__L_e', ...
        'EX_thr__L_e', ...
        'EX_trp__L_e', ...
        'EX_tyr__L_e', ...
        'EX_val__L_e', ...
        'EX_gtp_e', ... % nucleic acids
        'EX_gsn_e', ...
        'EX_csn_e', ...
        'EX_ade_e', ...
        'EX_thym_e', ...
        'EX_gmp_e', ...
        'EX_dgmp_e', ...
        'EX_3gmp_e', ...
        'EX_cmp_e', ...
        'EX_dcmp_e', ...
        'EX_3cmp_e', ...
        'EX_amp_e', ...
        'EX_damp_e', ...
        'EX_3amp_e', ...
        'EX_dtmp_e', ...
        'EX_ump_e', ...
        'EX_dump_e', ...
        'EX_3ump_e', ...
        'EX_uri_e', ...
        'EX_ins_e', ...
        'EX_enlipa_e', ... % lipids
        'EX_hdca_e', ...
        'EX_hdcea_e', ...
        'EX_ocdca_e', ...
        'EX_ocdcea_e', ...
        'EX_colipa_e', ...
        'EX_colipap_e', ...
        'EX_etha_e', ... % other
        'EX_pheme_e', ...
        'EX_ac_e', ...
        };
    
    yeast_extract_uptake_names = {'Thiamin exchange', ... % vitamins
        'Nicotinate exchange', ...
        '(R)-Pantothenate exchange', ...
        'Pyridoxamine exchange', ...
        'Pyridoxal exchange', ...
        'Pyridoxine exchange', ...
        'Biotin exchange', ...
        'Adenosylcobalamin exchange', ...
        'Cobinamide exchange', ...
        'Cob(I)alamin exchange', ...
        'Myo-Inositol exchange', ...
        'L-Ascorbate exchange', ...
        'Choline exchange', ...
        'Beta-Alanine exchange', ... % aminoacids
        'D-Alanine exchange', ...
        'L-Alanine exchange', ...
        'L-Arginine exchange', ...
        'L-Asparagine exchange', ...
        'L-Aspartate exchange', ...
        'D-Cysteine exchange', ...
        'L-Cysteine exchange', ...
        'L-Glutamate exchange', ...
        'L-Glutamine exchange', ...
        'Glycine exchange', ...
        'L-Histidine exchange', ...
        'L-Isoleucine exchange', ...
        'L-Leucine exchange', ...
        'L-Lysine exchange', ...
        'D-Methionine exchange', ...
        'L-Methionine exchange', ...
        'L-Phenylalanine exchange', ...
        'L-Proline exchange', ...
        'D-Serine exchange', ...
        'L-Serine exchange', ...
        'L-Threonine exchange', ...
        'L-Tryptophan exchange', ...
        'L-Tyrosine exchange', ...
        'L-Valine exchange', ...
        'GTP exchange', ... % nucleic acids
        'Guanosine exchange', ...
        'Cytosine exchange', ...
        'Adenine exchange', ...
        'Thymine exchange', ...
        'GMP exchange', ...
        'DGMP exchange', ...
        '3-GMP exchange', ...
        'CMP exchange', ...
        'DCMP exchange', ...
        '3-CMP exchange', ...
        'AMP exchange', ...
        'DAMP exchange', ...
        '3-AMP exchange', ...
        'DTMP exchange', ...
        'UMP exchange', ...
        'DUMP exchange', ...
        '3-UMP exchange', ...
        'Uridine exchange', ...
        'Inosine exchange', ...
        'Phosphoethanolamine KDO(2)-lipid (A) exchange', ... % lipids
        'Hexadecanoate (n-C16:0) exchange', ...
        'Hexadecenoate (n-C16:1) exchange', ...
        'Octadecanoate (n-C18:0) exchange', ...
        'Octadecenoate (n-C18:1) exchange', ...
        'Core oligosaccharide lipid A exchange', ...
        'Core oligosaccharide lipid A diphosphate exchange', ...
        'Ethanolamine exchange', ... % other
        'Protoheme exchange', ...
        'Acetate exchange', ...
        };
    
    medium_uptakes = {'EX_so4_e', ... % ions
        'EX_k_e', ...
        'EX_pi_e', ...
        'EX_na1_e', ... % other
        };
    
    medium_uptake_names = {'Sulfate exchange', ... % ions
        'K+ exchange', ...
        'Phosphate exchange', ...
        'Sodium exchange', ... % other
        };
    
    feed_uptakes = {'EX_nh4_e', ... % ions
        'EX_h2o_e',... % other
        'EX_glc__D_e', ...
        'EX_etoh_e', ...
        'EX_glyc_e', ...
        };
    
    feed_uptake_names = {'Ammonia exchange', ... % ions
        'H2O exchange', ... % other
        'Glucose exchange', ...
        'Ethanol exchange', ...
        'Glycerol exchange', ...
        };
    
    other_uptakes = {'EX_o2_e', ...
        'EX_ca2_e', ...
        'EX_h_e', ...
        'EX_mn2_e', ...
        'EX_cu_e', ...
        'EX_cu2_e', ...
        'EX_fe2_e', ...
        'EX_fe3_e', ...
        'EX_mg2_e', ...
        'EX_zn2_e', ...
        'EX_cl_e', ...
        'EX_co2_e', ...
        'EX_cobalt2_e', ...
        'EX_mobd_e', ...
        'EX_ni2_e', ...
        'EX_sel_e', ...
        'EX_slnt_e', ...
        'EX_tungs_e', ...
        };
    
    other_uptake_names = {'O2 exchange', ...
        'Calcium exchange', ...
        'H+ exchange', ...
        'Mn2+ exchange', ...
        'Cu+ exchange', ...
        'Cu2+ exchange', ...
        'Fe2+ exchange', ...
        'Fe3+ exchange', ...
        'Mg exchange', ...
        'Zinc exchange', ...
        'Chloride exchange', ...
        'CO2 exchange', ...
        'Co2+ exchange', ...
        'Molybdate exchange', ...
        'Ni2+ exchange', ...
        'Selenate exchange', ...
        'Selenite exchange', ...
        'Tungstate exchange', ...
        };
    
    uptakes = [yeast_extract_uptakes medium_uptakes feed_uptakes other_uptakes]';
    uptake_names = [yeast_extract_uptake_names medium_uptake_names feed_uptake_names other_uptake_names]';
end

function model = change_enzyme_activity(model, T_table, T, input_reaction_expression, pos_genes_in_react_expr, ixs_geni_sorted_by_length, ...
    tc, tf, tm, th)
    % tc, tf, tm and th are parameters to regulate fractional activity at
    % Tc, Tf, Tm and Th respectively
    
    % sort T_table so as to have genes in model.genes order
    enzyme = model.genes;
    Tc = NaN(length(model.genes), 1);
    Tf = NaN(length(model.genes), 1);
    To = NaN(length(model.genes), 1);
    Tm = NaN(length(model.genes), 1);
    Th = NaN(length(model.genes), 1);
    crit_temp = table(enzyme, Tc, Tf, To, Tm, Th, 'RowNames', model.genes);
    [a, b] = ismember(model.genes, T_table.enzyme);
    crit_temp(a, :) = T_table(b(a), :);
    T_table = crit_temp;
    clear crit_temp
    
    T = T*ones(size(T_table, 1), 1);
    
    case1 = T <= T_table.Tc;
    case2 = T > T_table.Tc & T <= T_table.Tf;
    case3 = T > T_table.Tf & T <= T_table.To;
    case4 = T > T_table.To & T <= T_table.Tm;
    case5 = T > T_table.Tm & T <= T_table.Th;
    case6 = T > T_table.Th;
    case_missing_info = not(case1 | case2 | case3 | case4 | case5 | case6); % some T is unavailable
    case7 = case_missing_info & T > T_table.Tc & T <= T_table.To; % Tc < T <= To with no Tf
    case8 = case_missing_info & T > T_table.To & T <= T_table.Th; % To < T <= Th with no Tm
    case9 = case_missing_info & T <= T_table.Tf; % T <= Tf with no Tc
    case10 = case_missing_info & T > T_table.Tm; % T > Tm with no Th
    case11 = case_missing_info & not(case7 | case8 | case9 | case10);
        
    x = ones(length(model.genes), 1);
    x(case1) = tc;
    x(case2) = (tf*T_table.Tc(case2)+(tc-tf)*T(case2)-tc*T_table.Tf(case2)) ./ (T_table.Tc(case2)-T_table.Tf(case2));
    x(case3) = (T_table.Tf(case3)+(tf-1)*T(case3)-tf*T_table.To(case3)) ./ (T_table.Tf(case3)-T_table.To(case3));
    x(case4) = (T_table.Tm(case4)+(tm-1)*T(case4)-tm*T_table.To(case4)) ./ (T_table.Tm(case4)-T_table.To(case4));
    x(case5) = (tm*T_table.Th(case5)+(tm-th)*T(case5)-th*T_table.To(case5)) ./ (T_table.Th(case5)-T_table.Tm(case5));
    x(case6) = th;
    x(case7) = (T_table.Tc(case7)+(tc-1)*T(case7)-tc*T_table.To(case7)) ./ (T_table.Tc(case7)-T_table.To(case7));
    x(case8) = (T_table.Th(case8)+(th-1)*T(case8)-th*T_table.To(case8)) ./ (T_table.Th(case8)-T_table.To(case8));
    x(case9) = tf;
    x(case10) = tm;
    x(case11) = 1;
        
    num_reaction_expression = zeros(length(input_reaction_expression), 1);
    % searches for all the strings of the kind min(NUM.NUM,NUM.NUM) or max(NUM.NUM,NUM.NUM) or min((NUM.NUM),NUM.NUM) or max((NUM.NUM),NUM.NUM) or min((NUM.NUM),(NUM.NUM)) or max(NUM.NUM,(NUM.NUM)) or min(NUM.NUM,(NUM.NUM)) or max((NUM.NUM),(NUM.NUM))
    to_replace = 'min.\d*+\.+\d*,\d*+\.+\d*.|max.\d*+\.+\d*,\d*+\.+\d*.|min..\d*+\.+\d*.,\d*+\.+\d*.|max..\d*+\.+\d*.,\d*+\.+\d*.|min..\d*+\.+\d*.,.\d*+\.+\d*..|max..\d*+\.+\d*.,.\d*+\.+\d*..|min.\d*+\.+\d*,.\d*+\.+\d*..|max.\d*+\.+\d*,.\d*+\.+\d*..';
    to_replace_nan1 = '|min.NaN,\d*+\.+\d*.|min.\d*+\.+\d*,NaN.|max.NaN,\d*+\.+\d*.|max.\d*+\.+\d*,NaN.|min..NaN.,\d*+\.+\d*.|min..\d*+\.+\d*.,NaN.|max..NaN.,\d*+\.+\d*.|max..\d*+\.+\d*.,NaN.|min..NaN.,.\d*+\.+\d*..|min..\d*+\.+\d*.,.NaN..|max..NaN.,.\d*+\.+\d*..|max..\d*+\.+\d*.,.NaN..|min.NaN,.\d*+\.+\d*..|min.\d*+\.+\d*,.NaN..|max.NaN,.\d*+\.+\d*..|max.\d*+\.+\d*,.NaN..';
    to_replace_nan2 = '|min.NaN,NaN.|max.NaN,NaN.|min..NaN.,NaN.|max..NaN.,NaN.|min..NaN.,.NaN..|max..NaN.,.NaN..|min.NaN,.NaN..|max.NaN,.NaN..';
    to_replace = [to_replace to_replace_nan1 to_replace_nan2];

    reaction_expression = input_reaction_expression;
    for i = ixs_geni_sorted_by_length
        gene_positions = pos_genes_in_react_expr{i};
        for j = 1:length(gene_positions) % for each string of reaction_expression, we replace the substring 'bXXXX' with the number representing its enzyme activity
            reaction_expression{gene_positions(j)} = strrep(reaction_expression{gene_positions(j)}, model.genes{i}, num2str(x(i),'%.15f'));
        end
    end
    reaction_expression(cellfun(@isempty, reaction_expression)) = {'1.0'};
    
    for i = 1:length(num_reaction_expression)
        str = reaction_expression{i};
        num_parenthesis = numel(strfind(str, ')'));
        while (num_parenthesis > 32) % if there are more than 32 parentheses, matlab is unable to run EVAL, so we need to reduce these parentheses manually by starting to eval smaller pieces of the string
            substrings_to_replace = regexp(str, to_replace, 'match');
            if isempty(substrings_to_replace)
                num_parenthesis = 0;
            else
                for j = 1:numel(substrings_to_replace)
                    ss_rep = substrings_to_replace{j};
                    str = strrep(str, ss_rep, num2str(eval(ss_rep), '%.15f'));
                end
                num_parenthesis = numel(strfind(str, ')'));
            end
        end
        str = regexprep(str, '/', '');
        num_reaction_expression(i) = eval(str); % evaluates the cells like they are numerical expressions (so as to compute min and max of enzyme activities)
    end
    
    model.lb = model.lb.*num_reaction_expression;
    model.ub = model.ub.*num_reaction_expression;
end

function [MinimizedFlux, modelIrrev] = my_pFBA(modelIrrev, GeneOption)
% This function finds the minimum flux through the network and returns the
% minimized flux and an irreversible model convert model to irrev

    FBAsoln = optimizeCbModel(modelIrrev);
    modelIrrev.lb(modelIrrev.c==1) = FBAsoln.f;
    % add pseudo-metabolite to measure flux through network

    if nargin==1
        GeneOption=0;
    end
    
    %Add the metabolite
    modelIrrev = addMetabolite(modelIrrev,'fluxMeasure');
    %Then set all the Stoichiometric entries.
    
    if GeneOption==0 % signal that you want to minimize the sum of all gene and non-gene associated fluxes        
        modelIrrev.S(end,:) = ones(size(modelIrrev.S(1,:)));
    elseif GeneOption==1 % signal that you want to minimize the sum of only gene-associated fluxes
        %find all reactions which are gene associated
        Ind=find(sum(modelIrrev.rxnGeneMat,2)>0);
        modelIrrev.S(end,:) = zeros(size(modelIrrev.S(1,:)));
        modelIrrev.S(end,Ind) = 1;
    elseif GeneOption==2 % signal that you want to minimize the sum of only NON gene-associated fluxes
        %find all reactions which are gene associated
        Ind=find(sum(modelIrrev.rxnGeneMat,2)==0);
        modelIrrev.S(end,:) = zeros(size(modelIrrev.S(1,:)));
        modelIrrev.S(end,Ind) = 1;
    end   

    % add a pseudo reaction that measures the flux through the network
    modelIrrev = addReaction(modelIrrev,'netFlux','metaboliteList',{'fluxMeasure'},'stoichCoeffList',[-1],...
        'reversible',false,'lowerBound',0,'upperBound',inf,'objectiveCoef',0,'printLevel',-1);

    % set the flux measuring demand as the objective
    modelIrrev.c = zeros(length(modelIrrev.rxns),1);
    modelIrrev = changeObjective(modelIrrev, 'netFlux');

    % minimize the flux measuring demand (netFlux)
    MinimizedFlux = optimizeCbModel(modelIrrev,'min');
end
